---
# The main openstack site deployment playbook

- hosts: all
  vars_files:
    - group_vars/interfaces-1604
    
  roles:
   - common
  
   
- hosts: openstack-ubu-controller
  roles:
   - controller

- hosts: openstack-ubu-compute
  roles:
   - compute
 
- hosts: openstack-ubu-compute2
  roles:
   - compute2
 
