---
# The main openstack site deployment playbook
- include: group_vars/interfaces-1404
  when: ubuntu=='u1404'

- include: group_vars/interfaces-1604
  when: ubuntu=='u1604'

- hosts: all

  roles:
   - common
  
   
- hosts: openstack-ubu-controller
  roles:
   - controller

- hosts: openstack-ubu-compute
  roles:
   - compute
 
- hosts: openstack-ubu-compute2
  roles:
   - compute2
 
