---
# Tasks for the base controller node

- name: preseed debconf for Mysql
  shell: echo "mysql-server mysql-server/root_password {{ mysql_root_pass }}" >> pkg-preseed
  
- name: preseed debconf for Mysql
  shell: echo "mysql-server mysql-server/root_password_again {{ mysql_root_pass }}" >> pkg-preseed
  
- name: preseed debconf for Mysql
  shell: echo "mysql-server- mysql-server/start_on_boot boolean true" >> pkg-preseed 
  
- name: apply the preseed
  shell: debconf-set-selections pkg-preseed

- name: Install the base packages
  apt: pkg={{ item }} state=latest
  with_items: 
   - mysql-client
   - mysql-server
   - ntp
   - python-mysqldb
   - rabbitmq-server
   - git
   - lvm2
   - open-iscsi
   - python-dev
   - libmysqlclient-dev 
   - libffi-dev
   - libpq-dev
   - libssl-dev
   - python-libvirt
   - libxml2-dev
   - libxslt1-dev
   - mysql-client
   - apache2
   - libapache2-mod-wsgi
   - memcached
   - python-memcache
   - gettext
   - dnsmasq
   - conntrack
   - ipset
   
- name: Install the openvswitch packages when needed
  apt: pkg={{ item }} state=latest
  with_items:
   - openvswitch-switch
  when: ml2_environment == 'openvswitch'

- name: Install required pip packages
  pip: name={{ item }}
  with_items:
#   - python-glanceclient
#   - python-keystoneclient 
   - python-openstackclient 
   - mydb repoze.lru
   - pbr
   - mysql-python

- name: start the services
  service: name={{ item }} state=started enabled=yes
  with_items:
   - mysql
   - rabbitmq-server
   - ntp
   
- name: set root password since preseed isn't working
  shell: creates=/etc/mysql/db.passwd mysqladmin -u root password mysql; touch /etc/mysql/db.passwd

- name: install pip packages
  shell: pip install repoze.lru pbr mysql-python

  






