---
# Tasks for the Horizon controller node

- name: Clone Horizon directory
  git: repo=https://github.com/openstack/horizon.git version={{openstack_version}}
       dest=/root/horizon

- name: Make directory in /var/lib
  file: path=/var/lib/openstack-dashboard state=directory owner=horizon group=horizon

- name: Make directory in var/www
  file: path=/var/www/static state=directory owner=horizon group=horizon

- name: Make directory in /var/www
  file: path=/var/www/wsgi state=directory owner=horizon group=horizon

- name: make the /etc/openstack directory if not already there
  file: path=/etc/openstack_dashboard state=directory owner=horizon group=horizon

- name: copy the openstack settings file
  template:  src=local_settings.j2 dest=/etc/openstack_dashboard/local_settings.py owner=horizon group=horizon

- name: link the local settings file
  file: src=/etc/openstack_dashboard/local_settings.py path=/root/horizon/openstack_dashboard/local/local_settings.py state=link

- name: modify the STATIC_ROOT setting
  replace: dest=/root/horizon/openstack_dashboard/settings.py regexp='STATIC_ROOT = None' replace="STATIC_ROOT = '/var/www/static'"

- name: modify the ROOT_PATH setting
  replace: dest=/root/horizon/openstack_dashboard/settings.py regexp='ROOT_PATH = os\.path\.dirname\(os\.path\.abspath\(__file__\)\)' replace="#ROOT_PATH = os.path.dirname(os\.path\.abspath(__file__))\nROOT_PATH = '/var/www'"

- name: copy dashboard/conf
  copy: src=/root/horizon/openstack_dashboard/conf dest=/var/www

- name: copy dashboard/themes
  copy: src=/root/horizon/openstack_dashboard/themes dest=/var/www
  
- name: execute run_tests
  shell: /root/horizon/run_tests.sh -V --compilemessages
  args:
    chdir: /root/horizon 
    
- name: Fix the v3 keystone policy file
  replace: dest=/etc/keystone/policy.v3cloudsample.json regexp='"cloud_admin"{{ ":" }} "role{{ ":" }}admin and \(token\.is_admin_project{{ ":" }}True or domain_id{{ ":" }}admin_domain_id\)",' replace='"cloud_admin"{{ ":" }} "rule{{ ":" }}admin_required and domain_id{{ ":" }}domain_id",' 

- name: copy the v3 policy file to where horizon expects it
  copy: src=/etc/keystone/policy.v3cloudsample.json dest=/root/horizon/openstack_dashboard/conf/
  
- name: install horizon
  shell: pip install -U .
  args:
     chdir: /root/horizon

- name: collect static
  shell: /root/horizon/manage.py collectstatic --noinput
  args:
    chdir: /root/horizon

- name: Build the wsgi file
  shell: /root/horizon/manage.py make_web_conf --wsgi --force
  args:
    chdir: /root/horizon

- name: copy the wsgi files
  copy: src=/root/horizon/openstack_dashboard/wsgi/ dest=/var/www/wsgi owner=horizon group=horizon 

- name: Build the apache conf file
  shell: /root/horizon/manage.py make_web_conf --apache > /etc/apache2/sites-available/openstack.conf
  args:
    chdir: /root/horizon

- name: copy even more static
  copy: src=/usr/local/lib/python2.7/dist-packages/openstack_dashboard/static/ dest=/var/www/static owner=horizon group=horizon
  
- name: copy some static stuff
  copy: src=/root/horizon/openstack_dashboard/dashboards/project/static/dashboard/project dest=/var/www/static/dashboard/  owner=horizon group=horizon

- name: copy more static stuff
  copy: src=/root/horizon/openstack_dashboard/dashboards/admin/static/dashboard/admin dest=/var/www/static/dashboard/  owner=horizon group=horizon

- name: Build a directory
  file: path=/var/www/static/horizon/lib/font-awesome state=directory owner=horizon group=horizon

#- name: link the fonts
#  file: src=/usr/local/lib/python2.7/dist-packages/xstatic/pkg/font_awesome/data/fonts path=/var/www/static/horizon/lib/font-awesome/fonts state=link

- name: add a link
  file: src=/var/www/static path=/usr/local/lib/python2.7/dist-packages/static state=link

- name: correct permissions
  shell: chown -R horizon:horizon /var/www/static

- name: disable default site
  shell: a2dissite 000-default.conf

- name: enable openstack site
  shell: a2ensite openstack

- name: restart apache
  service:  name=apache2 state=restarted enabled=yes
  
- name: correct /var/lib/openstack_dashboard permissions
  shell: chown -R /var/lib/openstack_dashboard
 
- name: Clone the novnc repo
  git: repo=https://github.com/kanaka/noVNC dest=/root/noVNC

- name: create a destination directory for the novnc files
  file: path=/usr/share/novnc state=directory

- name: copy the novnc files
  copy: src=/root/noVNC/ dest=/usr/share/novnc

- name: install some packages novnc needs
  apt: pkg={{ item }} state=latest
  with_items:
       - libjs-jquery
       - libjs-sphinxdoc
       - libjs-swfobject
       - libjs-underscore

- name: copy the novnc upstart file
  copy: src=nova-novncproxy.conf dest=/etc/init/nova-novncproxy.conf
  when: ubuntu == "u1404"

- name: Copy the nova novncproxy systemd file
  copy: src=nova-novncproxy.service dest=/lib/systemd/system/nova-novncproxy.service
  notify: restart neutron
  when: ubuntu == "u1604"

- name: Copy the nova novncproxy systemd init file
  copy: src=nova-novncproxy dest=/etc/init.d/nova-novncproxy mode=755
  notify: restart neutron
  when: ubuntu == "u1604"

- name: Start the novnc process
  service: name=nova-novncproxy state=started enabled=yes
