---
# Tasks for the nova controller node

- name: Create the nova user
  user: home="/var/lib/nova" createhome=yes system=yes shell=/bin/false name=nova

- name: use git to clone the nova git repo
  git: repo=https://github.com/openstack/nova.git version={{openstack_version}}
       dest=/root/nova

- name: make nova dir
  file: owner=nova group=nova state=directory path=/etc/nova

- name: make nova log dir
  file: owner=nova group=nova state=directory path=/var/log/nova

- name: install the nova etc dir files
  shell: cp -r nova/etc/nova/* /etc/nova/
  args:
     chdir: /root 

- name: install the nova etc dir files
  shell: cp -R nova/etc/nova/rootwrap.d/* /etc/nova/rootwrap.d
  args:
     chdir: /root  

- name: install the nova files
  shell: pip install -U . -c ../upper-constraints.txt
  args:
     chdir: /root/nova

- name: Setup DB for nova
  shell: creates=/var/lib/mysql/nova mysql -u root -p{{ mysql_root_pass }} -e "CREATE DATABASE nova;"

- name: Give rights to nova user.
  mysql_user: login_user=root login_password={{ mysql_root_pass }} name=nova password={{ nova_db_pass }} priv=*.*:ALL host='localhost' state=present

- name: Give rights to nova user.
  mysql_user: login_user=root login_password={{ mysql_root_pass }} name=nova password={{ nova_db_pass }} priv=*.*:ALL host='%' state=present
  
- name: Setup DB for nova-api
  shell: creates=/var/lib/mysql/nova_api mysql -u root -p{{ mysql_root_pass }} -e "CREATE DATABASE nova_api;"

- name: Give rights to nova user.
  mysql_user: login_user=root login_password={{ mysql_root_pass }} name=nova_api password={{ nova_db_pass }} priv=*.*:ALL host='localhost' state=present

- name: Give rights to nova user.
  mysql_user: login_user=root login_password={{ mysql_root_pass }} name=nova_api password={{ nova_db_pass }} priv=*.*:ALL host='%' state=present

- name: copy configuration file for nova
  template: src=liberty-nova.conf.j2 dest=/etc/nova/nova.conf
  when: openstack_version == "stable/liberty"

- name: copy configuration file for nova
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf
  when: openstack_version == "stable/mitaka" or openstack_version == "stable/newton"

- name: copy configuration file for nova
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf
  when: openstack_version == "HEAD"

- name: Copy nova sudoers file
  copy: src=nova_sudoers dest=/etc/sudoers.d/nova_sudoers mode=440
  
- name: DB sync for the nova services
  shell: nova-manage db sync; touch /etc/nova/db.synced creates=/etc/nova/db.synced

- name: DB sync for the nova api services
  shell: nova-manage api_db sync; touch /etc/nova/api-db.synced creates=/etc/nova/api-db.synced

- name: Copy the nova-api upstart files
  copy: src=nova-api.conf dest=/etc/init/nova-api.conf
  when: ubuntu == "u1404"

- name: Copy the api systemd file
  copy: src=nova-api.service dest=/lib/systemd/system/nova-api.service
  when: ubuntu == "u1604"

- name: Copy the api systemd init file
  copy: src=nova-api dest=/etc/init.d/nova-api mode=755
  when: ubuntu == "u1604"

- name: Copy the nova-cert upstart files
  copy: src=nova-cert.conf dest=/etc/init/nova-cert.conf
  when: ubuntu == "u1404"

- name: Copy the cert systemd file
  copy: src=nova-cert.service dest=/lib/systemd/system/nova-cert.service
  when: ubuntu == "u1604"

- name: Copy the cert systemd init file
  copy: src=nova-cert dest=/etc/init.d/nova-cert mode=755
  when: ubuntu == "u1604"

- name: Copy the nova-consoleauth upstart files
  copy: src=nova-consoleauth.conf dest=/etc/init/nova-consoleauth.conf
  when: ubuntu == "u1404"

- name: Copy the consoleauth systemd file
  copy: src=nova-consoleauth.service dest=/lib/systemd/system/nova-consoleauth.service
  when: ubuntu == "u1604"

- name: Copy the consoleauth systemd init file
  copy: src=nova-consoleauth dest=/etc/init.d/nova-consoleauth mode=755
  when: ubuntu == "u1604"

- name: Copy the nova-conductor upstart files
  copy: src=nova-conductor.conf dest=/etc/init/nova-conductor.conf
  when: ubuntu == "u1404"

- name: Copy the conductor systemd file
  copy: src=nova-conductor.service dest=/lib/systemd/system/nova-conductor.service
  when: ubuntu == "u1604"

- name: Copy the conductor systemd init file
  copy: src=nova-conductor dest=/etc/init.d/nova-conductor mode=755
  when: ubuntu == "u1604"

- name: Copy the nova-scheduler upstart files
  copy: src=nova-scheduler.conf dest=/etc/init/nova-scheduler.conf
  when: ubuntu == "u1404"

- name: Copy the scheduler systemd file
  copy: src=nova-scheduler.service dest=/lib/systemd/system/nova-scheduler.service
  when: ubuntu == "u1604"

- name: Copy the conductor systemd init file
  copy: src=nova-scheduler dest=/etc/init.d/nova-scheduler mode=755
  when: ubuntu == "u1604"

- name: remove libvirt default network
  file: path=/etc/libvirt/qemu/networks/autostart/default.xml state=absent

- name: destroy the default network
  shell: virsh net-destroy default; touch /etc/nova/virbr0.stop creates=/etc/nova/virbr0.stop

- name: Start the services for nova
  service: name={{ item }} state=started enabled=yes
  with_items:
   - nova-api
   - nova-scheduler
   - nova-cert
   - nova-consoleauth
   - nova-conductor


